#!/bin/bash -l


#$ -l h_rt=12:00:00
#$ -P lau-bumc
#$ -N MSRG_container
#$ -j y
#$ -l cpu_arch=!bulldozer
#$ -o logs
#$ -m ea


if [ $# -eq 0 ]
  then
    echo "Please provide an input directory name, where fastq file is stored."; exit;
fi


IMAGE=/projectnb/lau-bumc/katia/MSRG/container/scc.simg

singularity exec -e -B /scratch -B /projectnb/scv/augustin/nlau_container/packages:/share -B /projectnb -B /projectnb/lau-bumc/katia/MSRG:/MSRG/  $IMAGE /MSRG/container/step1_gene-centric.sh $1



