#!/bin/bash -l


#$ -l h_rt=12:00:00
#$ -P lau-bumc
#$ -N MSRG_step1
#$ -j y
#$ -l cpu_arch=!bulldozer
#$ -o logs
#$ -m ea


if [ $# -eq 0 ]
  then
    echo "Please provide an input directory name, where fastq file is stored."; exit;
fi

# Path to the singularity image
IMAGE=/projectnb/lau-bumc/katia/simg/scc.simg

# Start singularity and run the script
singularity exec -e -B /share -B /projectnb -B /projectnb/lau-bumc/katia/MSRG:/MSRG/  $IMAGE /MSRG/scripts/step1_gene-centric.sh $1


